package shapes.model

/**
 * This file has been generated by the skorm gradle plugin.
 */

import com.republicate.kson.Json
import kotlin.uuid.Uuid
import kotlinx.datetime.*
import com.republicate.skorm.*
import kotlin.jvm.JvmName

@OptIn(kotlin.uuid.ExperimentalUuidApi::class)
class ShapesDatabase(processor: Processor): Database("shapes", processor), MutableDatabase {
    companion object {
        lateinit var instance: Database
        private fun isInstantiated() = this::instance.isInitialized
        val main: MainSchema by lazy { MainSchema(instance) }
        val other: OtherSchema by lazy { OtherSchema(instance) }
    }
    init {
        if (isInstantiated()) throw RuntimeException("ShapesDatabase instance already created")
        instance = this
    }
    override fun initialize() {
MainSchema.Person.initialize()
MainSchema.Country.initialize()
MainSchema.Friendship.initialize()
MainSchema.Gift.initialize()
MainSchema.Address.initialize()
MainSchema.Vip.initialize()
MainSchema.PersonAddress.initialize()
OtherSchema.Badge.initialize()
        super.initialize()
    }
    class MainSchema(db: Database): Schema("main", db), MutableSchema {
        enum class Level {
            low,
            high
        }
        enum class PersonKind {
            person,
            vip
        }
        enum class PersonNature {
            a,
            b
        }
        interface PersonFields {
            val personId: Int
            val name: String
            val rank: Level
            val nature: PersonNature
            val small: Short
            val tiny: Byte?
            val big: Long?
            val uid: Uuid?
            val meta: Json?
            val born: LocalDate?
            val seen: LocalDateTime?
            val kind: PersonKind
        }
        open class Person(entity: Entity = Companion): Instance(entity), MutableInstance, PersonFields {
            companion object: Entity("person", main), MutableEntity {
                override fun new(): Person = Person()
                // rows are read joined with the subtypes' tables: each comes back as the class its kind names
                override val source = "main.person LEFT JOIN main.base_vip USING (person_id)"
                override fun new(kind: String?): Person = when (kind) {
                    "person" -> new()
                    "vip" -> ShapesDatabase.MainSchema.Vip.new()
                    else -> throw SkormException("person rows carry no kind: a hierarchy is read with its subtypes joined")
                }
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Person?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Person>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Person>
                fun initialize() {
                    addField(Field("personId", "serial", true, true))
                    addField(Field("name", "varchar(50)", false, false))
                    addField(Field("rank", "level", false, false))
                    addField(Field("nature", "enum('a','b')", false, false))
                    addField(Field("small", "smallint", false, false))
                    addField(Field("tiny", "tinyint", false, false))
                    addField(Field("big", "biginteger", false, false))
                    addField(Field("uid", "uuid", false, false))
                    addField(Field("meta", "json", false, false))
                    addField(Field("born", "date", false, false))
                    addField(Field("seen", "timestamp", false, false))
                    addField(Field("kind", "person_kind", false, false))
                }
            }
            // a new row knows its kind before the database applies it; a subtype's init runs last and wins
            init { put("kind", "person") }
            override val personId: Int
                get() = getInt("personId")!!
            override var name: String
                get() = getString("name")!!
                set(v) { put("name", v) }
            override var rank: Level
                get() = getString("rank")!!.let { Level.valueOf(it) }
                set(v) { put("rank", v.toString()) }
            override var nature: PersonNature
                get() = getString("nature")!!.let { PersonNature.valueOf(it) }
                set(v) { put("nature", v.toString()) }
            override var small: Short
                get() = getShort("small")!!
                set(v) { put("small", v) }
            override var tiny: Byte?
                get() = getByte("tiny")
                set(v) { put("tiny", v) }
            override var big: Long?
                get() = getLong("big")
                set(v) { put("big", v) }
            override var uid: Uuid?
                get() = getUuid("uid")
                set(v) { put("uid", v) }
            override var meta: Json?
                get() = getJson("meta")
                set(v) { put("meta", v) }
            override var born: LocalDate?
                get() = getLocalDate("born")
                set(v) { put("born", v) }
            override var seen: LocalDateTime?
                get() = getLocalDateTime("seen")
                set(v) { put("seen", v) }
            override val kind: PersonKind
                get() = getString("kind")!!.let { PersonKind.valueOf(it) }
            // reverse foreign key
            suspend fun aFriendships(): Sequence<ShapesDatabase.MainSchema.Friendship> = query("aFriendships")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("aFriendships")
            fun aFriendshipsBlocking(): List<ShapesDatabase.MainSchema.Friendship> = blocking { aFriendships().toList() }
            // reverse foreign key
            suspend fun bFriendships(): Sequence<ShapesDatabase.MainSchema.Friendship> = query("bFriendships")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("bFriendships")
            fun bFriendshipsBlocking(): List<ShapesDatabase.MainSchema.Friendship> = blocking { bFriendships().toList() }
            // reverse foreign key
            suspend fun ownerAddresses(): Sequence<ShapesDatabase.MainSchema.Address> = query("ownerAddresses")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("ownerAddresses")
            fun ownerAddressesBlocking(): List<ShapesDatabase.MainSchema.Address> = blocking { ownerAddresses().toList() }
            // left to right n-n join
            suspend fun addresses(): Sequence<ShapesDatabase.MainSchema.Address> = query("addresses")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("addresses")
            fun addressesBlocking(): List<ShapesDatabase.MainSchema.Address> = blocking { addresses().toList() }
            // reverse foreign key
            suspend fun badges(): Sequence<ShapesDatabase.OtherSchema.Badge> = query("badges")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("badges")
            fun badgesBlocking(): List<ShapesDatabase.OtherSchema.Badge> = blocking { badges().toList() }
            // attribute Person.mainAddress
            suspend fun `mainAddress`() = retrieve<ShapesDatabase.MainSchema.Address?>("mainAddress")
            @JvmName("mainAddress")
            fun mainAddressBlocking() = blocking { `mainAddress`() }
            // attribute Person.forget
            suspend fun `forget`() = perform("forget")
            // attribute Person.counts
            suspend fun `counts`() = retrieve<Counts>("counts") as Counts
            @JvmName("counts")
            fun countsBlocking() = blocking { `counts`() }
            // attribute Person.cities
            suspend fun `cities`() = query<String>("cities")
            @JvmName("cities")
            fun citiesBlocking() = blocking { `cities`().toList() }
        }
        interface CountryFields {
            val code: String
            val label: String
        }
        open class Country(entity: Entity = Companion): Instance(entity), MutableInstance, CountryFields {
            companion object: Entity("country", main), MutableEntity {
                override fun new(): Country = Country()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Country?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Country>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Country>
                fun initialize() {
                    addField(Field("code", "char(2)", true, false))
                    addField(Field("label", "varchar(50)", false, false))
                }
            }
            override val code: String
                get() = getString("code")!!
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
            // reverse foreign key
            suspend fun addresses(): Sequence<ShapesDatabase.MainSchema.Address> = query("addresses")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("addresses")
            fun addressesBlocking(): List<ShapesDatabase.MainSchema.Address> = blocking { addresses().toList() }
        }
        interface FriendshipFields {
            val aId: Int
            val bId: Int
            val since: LocalDate
        }
        open class Friendship(entity: Entity = Companion): Instance(entity), MutableInstance, FriendshipFields {
            companion object: Entity("friendship", main), MutableEntity {
                override fun new(): Friendship = Friendship()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Friendship?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Friendship>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Friendship>
                fun initialize() {
                    addField(Field("aId", "int", true, false))
                    addField(Field("bId", "int", true, false))
                    addField(Field("since", "date", false, false))
                }
            }
            override val aId: Int
                get() = getInt("aId")!!
            override val bId: Int
                get() = getInt("bId")!!
            override var since: LocalDate
                get() = getLocalDate("since")!!
                set(v) { put("since", v) }
            // forward foreign key
            suspend fun a(): ShapesDatabase.MainSchema.Person = retrieve("a")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("a")
            fun aBlocking(): ShapesDatabase.MainSchema.Person = blocking { a() }
            // forward foreign key
            suspend fun b(): ShapesDatabase.MainSchema.Person = retrieve("b")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("b")
            fun bBlocking(): ShapesDatabase.MainSchema.Person = blocking { b() }
            // reverse foreign key
            suspend fun gifts(): Sequence<ShapesDatabase.MainSchema.Gift> = query("gifts")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("gifts")
            fun giftsBlocking(): List<ShapesDatabase.MainSchema.Gift> = blocking { gifts().toList() }
        }
        interface GiftFields {
            val label: String
            val aId: Int
            val bId: Int
        }
        open class Gift(entity: Entity = Companion): Instance(entity), MutableInstance, GiftFields {
            companion object: Entity("gift", main), MutableEntity {
                override fun new(): Gift = Gift()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Gift>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Gift>
                fun initialize() {
                    addField(Field("label", "varchar(20)", false, false))
                    addField(Field("aId", "int", false, false))
                    addField(Field("bId", "int", false, false))
                }
            }
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
            override var aId: Int
                get() = getInt("aId")!!
                set(v) { put("aId", v) }
            override var bId: Int
                get() = getInt("bId")!!
                set(v) { put("bId", v) }
            // forward foreign key
            suspend fun friendship(): ShapesDatabase.MainSchema.Friendship = retrieve("friendship")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("friendship")
            fun friendshipBlocking(): ShapesDatabase.MainSchema.Friendship = blocking { friendship() }
        }
        interface AddressFields {
            val addressId: Int
            val city: String
            val owner: Int
            val backup: Int?
            val code: String
        }
        open class Address(entity: Entity = Companion): Instance(entity), MutableInstance, AddressFields {
            companion object: Entity("address", main), MutableEntity {
                override fun new(): Address = Address()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Address?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Address>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Address>
                fun initialize() {
                    addField(Field("addressId", "serial", true, true))
                    addField(Field("city", "varchar(50)", false, false))
                    addField(Field("owner", "int", false, false))
                    addField(Field("backup", "int", false, false))
                    addField(Field("code", "char(2)", false, false))
                }
            }
            override val addressId: Int
                get() = getInt("addressId")!!
            override var city: String
                get() = getString("city")!!
                set(v) { put("city", v) }
            override var owner: Int
                get() = getInt("owner")!!
                set(v) { put("owner", v) }
            override var backup: Int?
                get() = getInt("backup")
                set(v) { put("backup", v) }
            override var code: String
                get() = getString("code")!!
                set(v) { put("code", v) }
            // forward foreign key
            suspend fun owner(): ShapesDatabase.MainSchema.Person = retrieve("owner")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("owner")
            fun ownerBlocking(): ShapesDatabase.MainSchema.Person = blocking { owner() }
            // forward foreign key
            suspend fun backup(): ShapesDatabase.MainSchema.Person? = retrieve("backup")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("backup")
            fun backupBlocking(): ShapesDatabase.MainSchema.Person? = blocking { backup() }
            // forward foreign key
            suspend fun country(): ShapesDatabase.MainSchema.Country = retrieve("country")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("country")
            fun countryBlocking(): ShapesDatabase.MainSchema.Country = blocking { country() }
            // right to left n-n join
            suspend fun persons(): Sequence<ShapesDatabase.MainSchema.Person> = query("persons")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("persons")
            fun personsBlocking(): List<ShapesDatabase.MainSchema.Person> = blocking { persons().toList() }
        }
        interface VipFields : ShapesDatabase.MainSchema.PersonFields {
        }
        open class Vip(entity: Entity = Companion): ShapesDatabase.MainSchema.Person(entity), VipFields {
            companion object: Entity("vip", main, ShapesDatabase.MainSchema.Person), MutableEntity {
                override fun new(): Vip = Vip()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Vip?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Vip>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Vip>
                fun initialize() {
                    addField(Field("personId", "serial", true, true))
                    addField(Field("name", "varchar(50)", false, false))
                    addField(Field("rank", "level", false, false))
                    addField(Field("nature", "enum('a','b')", false, false))
                    addField(Field("small", "smallint", false, false))
                    addField(Field("tiny", "tinyint", false, false))
                    addField(Field("big", "biginteger", false, false))
                    addField(Field("uid", "uuid", false, false))
                    addField(Field("meta", "json", false, false))
                    addField(Field("born", "date", false, false))
                    addField(Field("seen", "timestamp", false, false))
                    addField(Field("kind", "person_kind", false, false))
                }
            }
            // a new row knows its kind before the database applies it; a subtype's init runs last and wins
            init { put("kind", "vip") }
        }
        interface PersonAddressFields {
            val personId: Int
            val addressId: Int
        }
        open class PersonAddress(entity: Entity = Companion): Instance(entity), MutableInstance, PersonAddressFields {
            companion object: Entity("personAddress", main), MutableEntity {
                override fun new(): PersonAddress = PersonAddress()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<PersonAddress>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<PersonAddress>
                fun initialize() {
                    addField(Field("personId", "int", false, false))
                    addField(Field("addressId", "int", false, false))
                }
            }
            override var personId: Int
                get() = getInt("personId")!!
                set(v) { put("personId", v) }
            override var addressId: Int
                get() = getInt("addressId")!!
                set(v) { put("addressId", v) }
        }
        // attribute main.personCount
        suspend fun `personCount`() = eval<Int>("personCount")
        @JvmName("personCount")
        fun personCountBlocking() = blocking { `personCount`() }
        // attribute main.oldestBirth
        suspend fun `oldestBirth`() = eval<LocalDate?>("oldestBirth")
        @JvmName("oldestBirth")
        fun oldestBirthBlocking() = blocking { `oldestBirth`() }
        // attribute main.summary
        suspend fun `summary`() = retrieve<Json.Object>("summary")
        @JvmName("summary")
        fun summaryBlocking() = blocking { `summary`() }
        // attribute main.everybody
        suspend fun `everybody`() = query<ShapesDatabase.MainSchema.Person>("everybody")
        @JvmName("everybody")
        fun everybodyBlocking() = blocking { `everybody`().toList() }
    }
    class OtherSchema(db: Database): Schema("other", db), MutableSchema {
        interface BadgeFields {
            val label: String
            val personId: Int
        }
        open class Badge(entity: Entity = Companion): Instance(entity), MutableInstance, BadgeFields {
            companion object: Entity("badge", other), MutableEntity {
                override fun new(): Badge = Badge()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Badge>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Badge>
                fun initialize() {
                    addField(Field("label", "varchar(20)", false, false))
                    addField(Field("personId", "int", false, false))
                }
            }
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
            override var personId: Int
                get() = getInt("personId")!!
                set(v) { put("personId", v) }
            // forward foreign key
            suspend fun person(): ShapesDatabase.MainSchema.Person = retrieve("person")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("person")
            fun personBlocking(): ShapesDatabase.MainSchema.Person = blocking { person() }
        }
    }
}

