package shapes.model

/**
 * This file has been generated by the skorm gradle plugin.
 */

import com.republicate.kson.Json
import kotlin.uuid.Uuid
import kotlinx.datetime.*
import com.republicate.skorm.*

@OptIn(kotlin.uuid.ExperimentalUuidApi::class)
class ShapesDatabase(processor: Processor): Database("shapes", processor) {
    companion object {
        lateinit var instance: Database
        private fun isInstantiated() = this::instance.isInitialized
        val main: MainSchema by lazy { MainSchema(instance) }
        val other: OtherSchema by lazy { OtherSchema(instance) }
    }
    init {
        if (isInstantiated()) throw RuntimeException("ShapesDatabase instance already created")
        instance = this
    }
    override fun initialize() {
MainSchema.Person.initialize()
MainSchema.Country.initialize()
MainSchema.Friendship.initialize()
MainSchema.Gift.initialize()
MainSchema.Address.initialize()
MainSchema.Vip.initialize()
MainSchema.PersonAddress.initialize()
OtherSchema.Badge.initialize()
        super.initialize()
    }
    class MainSchema(db: Database): Schema("main", db) {
        enum class Level {
            low,
            high
        }
        enum class PersonNature {
            a,
            b
        }
        interface PersonFields {
            val name: String
            val rank: Level
            val nature: PersonNature
            val small: Short
            val tiny: Byte?
            val big: Long?
            val uid: Uuid?
            val meta: Json?
            val born: LocalDate?
            val seen: LocalDateTime?
            val personId: Int
        }
        open class Person: Instance(Companion), PersonFields {
            companion object: Entity("person", main) {
                override fun new(): Person = Person()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Person?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Person>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Person>
                fun initialize() {
                    addField(Field("name", "varchar(50)", false, false))
                    addField(Field("rank", "level", false, false))
                    addField(Field("nature", "enum('a','b')", false, false))
                    addField(Field("small", "smallint", false, false))
                    addField(Field("tiny", "tinyint", false, false))
                    addField(Field("big", "biginteger", false, false))
                    addField(Field("uid", "uuid", false, false))
                    addField(Field("meta", "json", false, false))
                    addField(Field("born", "date", false, false))
                    addField(Field("seen", "timestamp", false, false))
                    addField(Field("personId", "serial", true, true))
                }
            }
            override var name: String
                get() = getString("name")!!
                set(v) { put("name", v) }
            override var rank: Level
                get() = getString("rank")!!.let { Level.valueOf(it) }
                set(v) { put("rank", v.toString()) }
            override var nature: PersonNature
                get() = getString("nature")!!.let { PersonNature.valueOf(it) }
                set(v) { put("nature", v.toString()) }
            override var small: Short
                get() = getShort("small")!!
                set(v) { put("small", v) }
            override var tiny: Byte?
                get() = getByte("tiny")
                set(v) { put("tiny", v) }
            override var big: Long?
                get() = getLong("big")
                set(v) { put("big", v) }
            override var uid: Uuid?
                get() = getUuid("uid")
                set(v) { put("uid", v) }
            override var meta: Json?
                get() = getJson("meta")
                set(v) { put("meta", v) }
            override var born: LocalDate?
                get() = getLocalDate("born")
                set(v) { put("born", v) }
            override var seen: LocalDateTime?
                get() = getLocalDateTime("seen")
                set(v) { put("seen", v) }
            override val personId: Int
                get() = getInt("personId")!!
        }
        interface CountryFields {
            val code: String
            val label: String
        }
        open class Country: Instance(Companion), CountryFields {
            companion object: Entity("country", main) {
                override fun new(): Country = Country()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Country?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Country>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Country>
                fun initialize() {
                    addField(Field("code", "char(2)", true, false))
                    addField(Field("label", "varchar(50)", false, false))
                }
            }
            override val code: String
                get() = getString("code")!!
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
        }
        interface FriendshipFields {
            val aId: Int
            val bId: Int
            val since: LocalDate
        }
        open class Friendship: Instance(Companion), FriendshipFields {
            companion object: Entity("friendship", main) {
                override fun new(): Friendship = Friendship()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Friendship?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Friendship>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Friendship>
                fun initialize() {
                    addField(Field("aId", "int", true, false))
                    addField(Field("bId", "int", true, false))
                    addField(Field("since", "date", false, false))
                }
            }
            override val aId: Int
                get() = getInt("aId")!!
            override val bId: Int
                get() = getInt("bId")!!
            override var since: LocalDate
                get() = getLocalDate("since")!!
                set(v) { put("since", v) }
        }
        interface GiftFields {
            val label: String
            val aId: Int
            val bId: Int
        }
        open class Gift: Instance(Companion), GiftFields {
            companion object: Entity("gift", main) {
                override fun new(): Gift = Gift()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Gift>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Gift>
                fun initialize() {
                    addField(Field("label", "varchar(20)", false, false))
                    addField(Field("aId", "int", false, false))
                    addField(Field("bId", "int", false, false))
                }
            }
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
            override var aId: Int
                get() = getInt("aId")!!
                set(v) { put("aId", v) }
            override var bId: Int
                get() = getInt("bId")!!
                set(v) { put("bId", v) }
        }
        interface AddressFields {
            val city: String
            val owner: Int
            val backup: Int?
            val code: String
            val addressId: Int
        }
        open class Address: Instance(Companion), AddressFields {
            companion object: Entity("address", main) {
                override fun new(): Address = Address()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Address?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Address>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Address>
                fun initialize() {
                    addField(Field("city", "varchar(50)", false, false))
                    addField(Field("owner", "int", false, false))
                    addField(Field("backup", "int", false, false))
                    addField(Field("code", "char(2)", false, false))
                    addField(Field("addressId", "serial", true, true))
                }
            }
            override var city: String
                get() = getString("city")!!
                set(v) { put("city", v) }
            override var owner: Int
                get() = getInt("owner")!!
                set(v) { put("owner", v) }
            override var backup: Int?
                get() = getInt("backup")
                set(v) { put("backup", v) }
            override var code: String
                get() = getString("code")!!
                set(v) { put("code", v) }
            override val addressId: Int
                get() = getInt("addressId")!!
        }
        interface VipFields {
        }
        open class Vip: Instance(Companion), VipFields {
            companion object: Entity("vip", main) {
                override fun new(): Vip = Vip()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Vip>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Vip>
                fun initialize() {
                }
            }
        }
        interface PersonAddressFields {
            val personId: Int
            val addressId: Int
        }
        open class PersonAddress: Instance(Companion), PersonAddressFields {
            companion object: Entity("personAddress", main) {
                override fun new(): PersonAddress = PersonAddress()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<PersonAddress>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<PersonAddress>
                fun initialize() {
                    addField(Field("personId", "int", false, false))
                    addField(Field("addressId", "int", false, false))
                }
            }
            override var personId: Int
                get() = getInt("personId")!!
                set(v) { put("personId", v) }
            override var addressId: Int
                get() = getInt("addressId")!!
                set(v) { put("addressId", v) }
        }
    }
    class OtherSchema(db: Database): Schema("other", db) {
        interface BadgeFields {
            val label: String
            val personId: Int
        }
        open class Badge: Instance(Companion), BadgeFields {
            companion object: Entity("badge", other) {
                override fun new(): Badge = Badge()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Badge>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Badge>
                fun initialize() {
                    addField(Field("label", "varchar(20)", false, false))
                    addField(Field("personId", "int", false, false))
                }
            }
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
            override var personId: Int
                get() = getInt("personId")!!
                set(v) { put("personId", v) }
        }
    }
}

