package com.republicate.skorm.jdbc

import com.republicate.skorm.AttributeHolder
import com.republicate.skorm.Database
import com.republicate.skorm.Entity
import com.republicate.skorm.Field
import com.republicate.skorm.QueryResult
import com.republicate.skorm.Schema
import com.republicate.skorm.core.CoreProcessor
import com.republicate.skorm.core.QueryDefinition
import com.republicate.skorm.core.SimpleQuery
import com.republicate.skorm.mutationAttribute
import com.republicate.skorm.transaction
import kotlinx.coroutines.test.runTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

/**
 * Ambient (coroutine-scoped) transactions over a real H2 database.
 */
class AmbientTransactionTest {

    private class Fixture(dbName: String, url: String) {
        val connector = JdbcConnector(url)
        val processor = CoreProcessor(connector)
        val database = object: Database(dbName, processor) {}
        val schema = object: Schema("tx", database) {}
        val book = object: Entity("book", schema) {}

        init {
            connector.initialize()
            connector.mutate(null, "CREATE SCHEMA IF NOT EXISTS TX")
            connector.mutate(null, "CREATE TABLE IF NOT EXISTS TX.BOOK (BOOK_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, TITLE VARCHAR(100))")
            book.addField(Field("bookId", "int", isPrimary = true, isGenerated = true))
            book.addField(Field("title", "varchar(100)"))
            schema.mutationAttribute("clearTitles", emptySet())
            processor.define("${(schema as AttributeHolder).path}/clearTitles",
                SimpleQuery("tx", QueryDefinition("UPDATE TX.BOOK SET TITLE = 'cleared';", emptyList())))
            database.initialize()
        }

        fun newBook(title: String) = book.new().apply { put("title", title) }

        // counts through the autocommit pool: blind to uncommitted transactions
        fun count(where: String = "") = scalarLong(connector.query("tx", "SELECT COUNT(*) FROM TX.BOOK $where"))

        fun clear() = connector.mutate("tx", "DELETE FROM TX.BOOK")
    }

    companion object {
        private val f1 by lazy { Fixture("test1", "jdbc:h2:mem:ambient_tx1;DB_CLOSE_DELAY=-1") }
        private val f2 by lazy { Fixture("test2", "jdbc:h2:mem:ambient_tx2;DB_CLOSE_DELAY=-1") }

        private fun scalarLong(result: QueryResult): Long {
            val value = (result.values.next()[0] as Number).toLong()
            while (result.values.hasNext()) result.values.next() // release the statement
            return value
        }
    }

    @BeforeTest
    fun clean() {
        f1.clear()
        f2.clear()
    }

    @Test
    fun commitOnNormalExit() = runTest {
        f1.database.transaction("tx") {
            f1.newBook("one").insert()
            f1.newBook("two").insert()
            assertEquals(0, f1.count(), "uncommitted rows visible outside the transaction")
        }
        assertEquals(2, f1.count())
    }

    @Test
    fun rollbackOnException() = runTest {
        assertFailsWith<IllegalStateException> {
            f1.database.transaction("tx") {
                f1.newBook("doomed").insert()
                throw IllegalStateException("boom")
            }
        }
        assertEquals(0, f1.count())
    }

    @Test
    fun generatedKeyInsideTransaction() = runTest {
        f1.database.transaction("tx") {
            val book = f1.newBook("keyed")
            book.insert()
            assertEquals(true, book.getInt("bookId")!! > 0)
        }
    }

    @Test
    fun nestedBlockJoinsEnclosingTransaction() = runTest {
        f1.database.transaction("tx") {
            f1.newBook("outer").insert()
            f1.database.transaction("tx") {
                f1.newBook("inner").insert()
            }
            assertEquals(0, f1.count(), "inner block exit must not commit")
        }
        assertEquals(2, f1.count())
    }

    @Test
    fun nestedBlockRollsBackWithEnclosingTransaction() = runTest {
        assertFailsWith<IllegalStateException> {
            f1.database.transaction("tx") {
                f1.newBook("outer").insert()
                f1.database.transaction("tx") {
                    f1.newBook("inner").insert()
                }
                throw IllegalStateException("boom")
            }
        }
        assertEquals(0, f1.count())
    }

    @Test
    fun otherDatabaseKeepsItsOwnProcessor() = runTest {
        assertFailsWith<IllegalStateException> {
            f1.database.transaction("tx") {
                f2.newBook("elsewhere").insert() // f2 has no ambient transaction: autocommit
                f1.newBook("doomed").insert()
                throw IllegalStateException("boom")
            }
        }
        assertEquals(0, f1.count())
        assertEquals(1, f2.count())
    }

    @Test
    fun entityOpAndSchemaAttributeAreAtomic() = runTest {
        f1.newBook("pre").insert()
        f1.database.transaction("tx") {
            f1.newBook("new").insert()
            f1.schema.perform("clearTitles")
        }
        assertEquals(2, f1.count("WHERE TITLE = 'cleared'"))
        assertFailsWith<IllegalStateException> {
            f1.database.transaction("tx") {
                f1.newBook("other").insert()
                f1.schema.perform("clearTitles")
                throw IllegalStateException("boom")
            }
        }
        assertEquals(2, f1.count())
        assertEquals(2, f1.count("WHERE TITLE = 'cleared'"))
    }

    @Test
    fun concurrentTransactionsGetDistinctConnections() = runTest {
        val tx1 = f1.connector.begin("tx")
        val tx2 = f1.connector.begin("tx")
        try {
            tx1.mutate("tx", "INSERT INTO TX.BOOK (TITLE) VALUES ('t1')")
            // sharing tx1's connection would expose its uncommitted row
            assertEquals(0, scalarLong(tx2.query("tx", "SELECT COUNT(*) FROM TX.BOOK")))
        } finally {
            tx1.rollback()
            tx2.rollback()
        }
    }
}
