package com.republicate.skorm.jdbc

import com.republicate.skorm.Connector
import com.republicate.skorm.Database
import com.republicate.skorm.Entity
import com.republicate.skorm.Field
import com.republicate.skorm.MutableInstanceImpl
import com.republicate.skorm.MutableDatabase
import com.republicate.skorm.MutableEntity
import com.republicate.skorm.MutableInstance
import com.republicate.skorm.MutableSchema
import com.republicate.skorm.QueryResult
import com.republicate.skorm.Schema
import com.republicate.skorm.core.CoreProcessor
import com.republicate.skorm.transaction
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * One store, two databases sharing a processor: the read-only one reads on the read connector,
 * the mutable one on its own, and a transaction of the mutable one is joined by both.
 */
class ReadConnectorTest {

    private class Counting(private val inner: Connector) : Connector by inner {
        var reads = 0
        override fun query(schema: String, query: String, vararg params: Any?): QueryResult {
            reads++
            return inner.query(schema, query, *params)
        }
    }

    private class Db(processor: CoreProcessor) : Database("store", processor)
    private class MutableDb(processor: CoreProcessor) : Database("store", processor), MutableDatabase {
        override val readOnly: Database by lazy { Db(processor) }
    }
    private class Sch(db: Database) : Schema("tx", db)
    private class MutableSch(db: Database) : Schema("tx", db), MutableSchema
    private class Ent(schema: Schema) : Entity("book", schema)
    private class MutableEnt(schema: Schema) : Entity("book", schema), MutableEntity {
        override fun new() = Row(this)
    }
    private class Row(entity: Entity) : MutableInstanceImpl(entity)

    private fun <E: Entity> E.withFields() = apply {
        addField(Field("bookId", "int", isPrimary = true, isGenerated = true))
        addField(Field("title", "varchar(100)"))
    }

    private val write = JdbcConnector("jdbc:h2:mem:read_connector;DB_CLOSE_DELAY=-1")
    private val read = Counting(JdbcConnector("jdbc:h2:mem:read_connector;DB_CLOSE_DELAY=-1"))
    private val processor = CoreProcessor(write, read)
    private val mutableBook = MutableEnt(MutableSch(MutableDb(processor))).withFields()
    private val book = Ent(Sch(Db(processor))).withFields()

    init {
        write.initialize()
        write.mutate(null, "CREATE SCHEMA IF NOT EXISTS TX")
        write.mutate(null, "CREATE TABLE IF NOT EXISTS TX.BOOK (BOOK_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, TITLE VARCHAR(100))")
        write.mutate("tx", "DELETE FROM TX.BOOK")
        mutableBook.schema.database.initialize()
        book.schema.database.initialize()
    }

    @Test
    fun readsRouteByDatabase() = runTest {
        mutableBook.browse().toList()
        assertEquals(0, read.reads, "the mutable database reads where it writes")
        book.browse().toList()
        assertEquals(1, read.reads, "the read-only database reads on the read connector")
    }

    @Test
    fun theReadOnlyDatabaseJoinsTheMutableTransaction() = runTest {
        mutableBook.schema.database.transaction {
            mutableBook.new().apply { put("title", "uncommitted") }.insert()
            assertEquals(listOf("uncommitted"), book.browse().map { it["title"] }.toList(), "the read-only database sees the transaction's row")
            assertEquals(0, read.reads, "inside the transaction it read on the transaction's connection")
        }
        assertEquals(listOf("uncommitted"), book.browse().map { it["title"] }.toList())
        assertEquals(1, read.reads)
    }
}
