package shapes.model

/**
 * This file has been generated by the skorm gradle plugin.
 *
 * Two halves: the read-only database, its schemas and row interfaces, and the mutable database
 * extending it, whose row interfaces add the writes. A row interface carries every accessor; the
 * class behind it (`XImpl`) is the storage, plus the blocking twins reflection-driven callers reach.
 */

import com.republicate.kson.Json
import kotlin.uuid.Uuid
import kotlinx.datetime.*
import com.republicate.skorm.*
import kotlin.jvm.JvmName
import shapes.model.ShapesDatabase.MainSchema.Level
import shapes.model.ShapesDatabase.MainSchema.PersonKind
import shapes.model.ShapesDatabase.MainSchema.PersonNature

/** The platform's registrations of the navigations and ksql attributes, run by initialize(). */
internal expect fun ShapesDatabase.registerAttributes()

@OptIn(kotlin.uuid.ExperimentalUuidApi::class)
open class ShapesDatabase(processor: Processor): Database("shapes", processor) {
    companion object {
        lateinit var instance: ShapesDatabase
        fun isInstantiated() = this::instance.isInitialized
        val main: MainSchema get() = instance.main
        val other: OtherSchema get() = instance.other
    }
    init {
        if (isInstantiated()) throw RuntimeException("ShapesDatabase instance already created")
        instance = this
    }
    open val main: MainSchema by lazy { MainSchema(this) }
    open val other: OtherSchema by lazy { OtherSchema(this) }
    override fun initialize() {
        main // the schema exists on this instance before the entities register
        other // the schema exists on this instance before the entities register
        MainSchema.Person.initialize()
        MainSchema.Country.initialize()
        MainSchema.Friendship.initialize()
        MainSchema.Gift.initialize()
        MainSchema.Address.initialize()
        MainSchema.Vip.initialize()
        MainSchema.PersonAddress.initialize()
        OtherSchema.Badge.initialize()
        super.initialize()
        registerAttributes()
    }
    open class MainSchema(db: Database): Schema("main", db) {
        enum class Level {
            low,
            high
        }
        enum class PersonKind {
            person,
            vip
        }
        enum class PersonNature {
            a,
            b
        }
        interface Person : Instance {
            companion object: Entity("person", ShapesDatabase.main) {
                override fun new(): Person = PersonImpl(this)
                // rows are read joined with the subtypes' tables: each comes back as the class its kind names
                override val source = "main.person LEFT JOIN main.base_vip USING (person_id)"
                override fun new(kind: String?): Person = when (kind) {
                    "person" -> new()
                    "vip" -> ShapesDatabase.MainSchema.Vip.new()
                    else -> throw SkormException("person rows carry no kind: a hierarchy is read with its subtypes joined")
                }
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Person?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Person>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Person>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("personId", "serial", true, true))
                    addField(Field("name", "varchar(50)", false, false))
                    addField(Field("rank", "level", false, false))
                    addField(Field("nature", "enum('a','b')", false, false))
                    addField(Field("small", "smallint", false, false))
                    addField(Field("tiny", "tinyint", false, false))
                    addField(Field("big", "biginteger", false, false))
                    addField(Field("uid", "uuid", false, false))
                    addField(Field("meta", "json", false, false))
                    addField(Field("born", "date", false, false))
                    addField(Field("seen", "timestamp", false, false))
                    addField(Field("kind", "person_kind", false, false))
                }
            }
            val personId: Int
                get() = getInt("personId")!!
            val name: String
                get() = getString("name")!!
            val rank: Level
                get() = getString("rank")!!.let { Level.valueOf(it) }
            val nature: PersonNature
                get() = getString("nature")!!.let { PersonNature.valueOf(it) }
            val small: Short
                get() = getShort("small")!!
            val tiny: Byte?
                get() = getByte("tiny")
            val big: Long?
                get() = getLong("big")
            val uid: Uuid?
                get() = getUuid("uid")
            val meta: Json?
                get() = getJson("meta")
            val born: LocalDate?
                get() = getLocalDate("born")
            val seen: LocalDateTime?
                get() = getLocalDateTime("seen")
            val kind: PersonKind
                get() = getString("kind")!!.let { PersonKind.valueOf(it) }
            // reverse foreign key
            suspend fun aFriendships(): Sequence<ShapesDatabase.MainSchema.Friendship> = query("aFriendships")
            // reverse foreign key
            suspend fun bFriendships(): Sequence<ShapesDatabase.MainSchema.Friendship> = query("bFriendships")
            // reverse foreign key
            suspend fun ownerAddresses(): Sequence<ShapesDatabase.MainSchema.Address> = query("ownerAddresses")
            // left to right n-n join
            suspend fun addresses(): Sequence<ShapesDatabase.MainSchema.Address> = query("addresses")
            // reverse foreign key
            suspend fun badges(): Sequence<ShapesDatabase.OtherSchema.Badge> = query("badges")
            // attribute Person.mainAddress
            suspend fun `mainAddress`() = retrieve<ShapesDatabase.MainSchema.Address?>("mainAddress")
            // attribute Person.counts
            suspend fun `counts`() = retrieve<Counts>("counts") as Counts
            // attribute Person.cities
            suspend fun `cities`() = query<String>("cities")
        }
        open class PersonImpl(entity: Entity = Person): InstanceImpl(entity), Person {
            // the blocking twin of `aFriendships()`: what a reflection-driven caller reaches under that name
            @JvmName("aFriendships")
            fun aFriendshipsBlocking(): List<ShapesDatabase.MainSchema.Friendship> = blocking { aFriendships().toList() }
            // the blocking twin of `bFriendships()`: what a reflection-driven caller reaches under that name
            @JvmName("bFriendships")
            fun bFriendshipsBlocking(): List<ShapesDatabase.MainSchema.Friendship> = blocking { bFriendships().toList() }
            // the blocking twin of `ownerAddresses()`: what a reflection-driven caller reaches under that name
            @JvmName("ownerAddresses")
            fun ownerAddressesBlocking(): List<ShapesDatabase.MainSchema.Address> = blocking { ownerAddresses().toList() }
            // the blocking twin of `addresses()`: what a reflection-driven caller reaches under that name
            @JvmName("addresses")
            fun addressesBlocking(): List<ShapesDatabase.MainSchema.Address> = blocking { addresses().toList() }
            // the blocking twin of `badges()`: what a reflection-driven caller reaches under that name
            @JvmName("badges")
            fun badgesBlocking(): List<ShapesDatabase.OtherSchema.Badge> = blocking { badges().toList() }
            @JvmName("mainAddress")
            fun mainAddressBlocking() = blocking { `mainAddress`() }
            @JvmName("counts")
            fun countsBlocking() = blocking { `counts`() }
            @JvmName("cities")
            fun citiesBlocking() = blocking { `cities`().toList() }
        }
        interface Country : Instance {
            companion object: Entity("country", ShapesDatabase.main) {
                override fun new(): Country = CountryImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Country?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Country>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Country>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("code", "char(2)", true, false))
                    addField(Field("label", "varchar(50)", false, false))
                }
            }
            val code: String
                get() = getString("code")!!
            val label: String
                get() = getString("label")!!
            // reverse foreign key
            suspend fun addresses(): Sequence<ShapesDatabase.MainSchema.Address> = query("addresses")
        }
        open class CountryImpl(entity: Entity = Country): InstanceImpl(entity), Country {
            // the blocking twin of `addresses()`: what a reflection-driven caller reaches under that name
            @JvmName("addresses")
            fun addressesBlocking(): List<ShapesDatabase.MainSchema.Address> = blocking { addresses().toList() }
        }
        interface Friendship : Instance {
            companion object: Entity("friendship", ShapesDatabase.main) {
                override fun new(): Friendship = FriendshipImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Friendship?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Friendship>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Friendship>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("aId", "int", true, false))
                    addField(Field("bId", "int", true, false))
                    addField(Field("since", "date", false, false))
                }
            }
            val aId: Int
                get() = getInt("aId")!!
            val bId: Int
                get() = getInt("bId")!!
            val since: LocalDate
                get() = getLocalDate("since")!!
            // forward foreign key
            suspend fun a(): ShapesDatabase.MainSchema.Person = retrieve("a")
            // forward foreign key
            suspend fun b(): ShapesDatabase.MainSchema.Person = retrieve("b")
            // reverse foreign key
            suspend fun gifts(): Sequence<ShapesDatabase.MainSchema.Gift> = query("gifts")
        }
        open class FriendshipImpl(entity: Entity = Friendship): InstanceImpl(entity), Friendship {
            // the blocking twin of `a()`: what a reflection-driven caller reaches under that name
            @JvmName("a")
            fun aBlocking(): ShapesDatabase.MainSchema.Person = blocking { a() }
            // the blocking twin of `b()`: what a reflection-driven caller reaches under that name
            @JvmName("b")
            fun bBlocking(): ShapesDatabase.MainSchema.Person = blocking { b() }
            // the blocking twin of `gifts()`: what a reflection-driven caller reaches under that name
            @JvmName("gifts")
            fun giftsBlocking(): List<ShapesDatabase.MainSchema.Gift> = blocking { gifts().toList() }
        }
        interface Gift : Instance {
            companion object: Entity("gift", ShapesDatabase.main) {
                override fun new(): Gift = GiftImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Gift>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Gift>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("label", "varchar(20)", false, false))
                    addField(Field("aId", "int", false, false))
                    addField(Field("bId", "int", false, false))
                }
            }
            val label: String
                get() = getString("label")!!
            val aId: Int
                get() = getInt("aId")!!
            val bId: Int
                get() = getInt("bId")!!
            // forward foreign key
            suspend fun friendship(): ShapesDatabase.MainSchema.Friendship = retrieve("friendship")
        }
        open class GiftImpl(entity: Entity = Gift): InstanceImpl(entity), Gift {
            // the blocking twin of `friendship()`: what a reflection-driven caller reaches under that name
            @JvmName("friendship")
            fun friendshipBlocking(): ShapesDatabase.MainSchema.Friendship = blocking { friendship() }
        }
        interface Address : Instance {
            companion object: Entity("address", ShapesDatabase.main) {
                override fun new(): Address = AddressImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Address?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Address>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Address>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("addressId", "serial", true, true))
                    addField(Field("city", "varchar(50)", false, false))
                    addField(Field("owner", "int", false, false))
                    addField(Field("backup", "int", false, false))
                    addField(Field("code", "char(2)", false, false))
                }
            }
            val addressId: Int
                get() = getInt("addressId")!!
            val city: String
                get() = getString("city")!!
            val owner: Int
                get() = getInt("owner")!!
            val backup: Int?
                get() = getInt("backup")
            val code: String
                get() = getString("code")!!
            // forward foreign key
            suspend fun owner(): ShapesDatabase.MainSchema.Person = retrieve("owner")
            // forward foreign key
            suspend fun backup(): ShapesDatabase.MainSchema.Person? = retrieve("backup")
            // forward foreign key
            suspend fun country(): ShapesDatabase.MainSchema.Country = retrieve("country")
            // right to left n-n join
            suspend fun persons(): Sequence<ShapesDatabase.MainSchema.Person> = query("persons")
        }
        open class AddressImpl(entity: Entity = Address): InstanceImpl(entity), Address {
            // the blocking twin of `owner()`: what a reflection-driven caller reaches under that name
            @JvmName("owner")
            fun ownerBlocking(): ShapesDatabase.MainSchema.Person = blocking { owner() }
            // the blocking twin of `backup()`: what a reflection-driven caller reaches under that name
            @JvmName("backup")
            fun backupBlocking(): ShapesDatabase.MainSchema.Person? = blocking { backup() }
            // the blocking twin of `country()`: what a reflection-driven caller reaches under that name
            @JvmName("country")
            fun countryBlocking(): ShapesDatabase.MainSchema.Country = blocking { country() }
            // the blocking twin of `persons()`: what a reflection-driven caller reaches under that name
            @JvmName("persons")
            fun personsBlocking(): List<ShapesDatabase.MainSchema.Person> = blocking { persons().toList() }
        }
        interface Vip : Instance, ShapesDatabase.MainSchema.Person {
            companion object: Entity("vip", ShapesDatabase.main, ShapesDatabase.MainSchema.Person) {
                override fun new(): Vip = VipImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Vip?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Vip>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Vip>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("personId", "serial", true, true))
                    addField(Field("name", "varchar(50)", false, false))
                    addField(Field("rank", "level", false, false))
                    addField(Field("nature", "enum('a','b')", false, false))
                    addField(Field("small", "smallint", false, false))
                    addField(Field("tiny", "tinyint", false, false))
                    addField(Field("big", "biginteger", false, false))
                    addField(Field("uid", "uuid", false, false))
                    addField(Field("meta", "json", false, false))
                    addField(Field("born", "date", false, false))
                    addField(Field("seen", "timestamp", false, false))
                    addField(Field("kind", "person_kind", false, false))
                }
            }
        }
        open class VipImpl(entity: Entity = Vip): ShapesDatabase.MainSchema.PersonImpl(entity), Vip {
        }
        interface PersonAddress : Instance {
            companion object: Entity("personAddress", ShapesDatabase.main) {
                override fun new(): PersonAddress = PersonAddressImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<PersonAddress>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<PersonAddress>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("personId", "int", false, false))
                    addField(Field("addressId", "int", false, false))
                }
            }
            val personId: Int
                get() = getInt("personId")!!
            val addressId: Int
                get() = getInt("addressId")!!
        }
        open class PersonAddressImpl(entity: Entity = PersonAddress): InstanceImpl(entity), PersonAddress {
        }
        // attribute main.personCount
        suspend fun `personCount`() = eval<Int>("personCount")
        @JvmName("personCount")
        fun personCountBlocking() = blocking { `personCount`() }
        // attribute main.oldestBirth
        suspend fun `oldestBirth`() = eval<LocalDate?>("oldestBirth")
        @JvmName("oldestBirth")
        fun oldestBirthBlocking() = blocking { `oldestBirth`() }
        // attribute main.summary
        suspend fun `summary`() = retrieve<Json.Object>("summary")
        @JvmName("summary")
        fun summaryBlocking() = blocking { `summary`() }
        // attribute main.everybody
        suspend fun `everybody`() = query<ShapesDatabase.MainSchema.Person>("everybody")
        @JvmName("everybody")
        fun everybodyBlocking() = blocking { `everybody`().toList() }
    }
    open class OtherSchema(db: Database): Schema("other", db) {
        interface Badge : Instance {
            companion object: Entity("badge", ShapesDatabase.other) {
                override fun new(): Badge = BadgeImpl(this)
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Badge>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Badge>
                fun initialize() {
                    if (fields.isNotEmpty()) return // the mutable database initializes its read-only sibling too
                    addField(Field("label", "varchar(20)", false, false))
                    addField(Field("personId", "int", false, false))
                }
            }
            val label: String
                get() = getString("label")!!
            val personId: Int
                get() = getInt("personId")!!
            // forward foreign key
            suspend fun person(): ShapesDatabase.MainSchema.Person = retrieve("person")
        }
        open class BadgeImpl(entity: Entity = Badge): InstanceImpl(entity), Badge {
            // the blocking twin of `person()`: what a reflection-driven caller reaches under that name
            @JvmName("person")
            fun personBlocking(): ShapesDatabase.MainSchema.Person = blocking { person() }
        }
    }
}
