package com.republicate.skorm.bookshelf

/**
 * This file has been generated by the skorm gradle plugin.
 */

import kotlinx.datetime.*
import com.republicate.skorm.*

class ExampleDatabase(processor: Processor): Database("example", processor) {
    companion object {
        lateinit var instance: Database
        private fun isInstantiated() = this::instance.isInitialized
        val bookshelf: BookshelfSchema by lazy { BookshelfSchema(instance) }
    }
    init {
        if (isInstantiated()) throw RuntimeException("ExampleDatabase instance already created")
        instance = this
    }
    override fun initialize() {
BookshelfSchema.Dude.initialize()
BookshelfSchema.Author.initialize()
BookshelfSchema.Book.initialize()
BookshelfSchema.Borrowing.initialize()
BookshelfSchema.Tag.initialize()
BookshelfSchema.BookTag.initialize()
        super.initialize()
    }
    class BookshelfSchema(db: Database): Schema("bookshelf", db) {
        enum class Genre {
            fiction,
            novel,
            essay,
            poetry
        }
        interface DudeFields {
            val dudeId: Int
            val name: String
        }
        open class Dude(entity: Entity = Companion): Instance(entity), DudeFields {
            companion object: Entity("dude", bookshelf) {
                override fun new(): Dude = Dude()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Dude?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Dude>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Dude>
                fun initialize() {
                    addField(Field("dudeId", "serial", true, true))
                    addField(Field("name", "varchar(100)", false, false))
                }
            }
            override val dudeId: Int
                get() = getInt("dudeId")!!
            override var name: String
                get() = getString("name")!!
                set(v) { put("name", v) }
        }
        interface AuthorFields {
            val authorId: Int
            val name: String
        }
        open class Author(entity: Entity = Companion): Instance(entity), AuthorFields {
            companion object: Entity("author", bookshelf) {
                override fun new(): Author = Author()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Author?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Author>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Author>
                fun initialize() {
                    addField(Field("authorId", "serial", true, true))
                    addField(Field("name", "varchar(100)", false, false))
                }
            }
            override val authorId: Int
                get() = getInt("authorId")!!
            override var name: String
                get() = getString("name")!!
                set(v) { put("name", v) }
        }
        interface BookFields {
            val bookId: Int
            val title: String
            val genre: Genre
            val donor: Int?
            val authorId: Int
        }
        open class Book(entity: Entity = Companion): Instance(entity), BookFields {
            companion object: Entity("book", bookshelf) {
                override fun new(): Book = Book()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Book?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Book>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Book>
                fun initialize() {
                    addField(Field("bookId", "serial", true, true))
                    addField(Field("title", "varchar(100)", false, false))
                    addField(Field("genre", "enum('fiction','novel','essay','poetry')", false, false))
                    addField(Field("donor", "int", false, false))
                    addField(Field("authorId", "int", false, false))
                }
            }
            override val bookId: Int
                get() = getInt("bookId")!!
            override var title: String
                get() = getString("title")!!
                set(v) { put("title", v) }
            override var genre: Genre
                get() = getString("genre")!!.let { Genre.valueOf(it) }
                set(v) { put("genre", v.toString()) }
            override var donor: Int?
                get() = getInt("donor")
                set(v) { put("donor", v) }
            override var authorId: Int
                get() = getInt("authorId")!!
                set(v) { put("authorId", v) }
        }
        interface BorrowingFields {
            val borrowingDate: LocalDate
            val restitutionDate: LocalDate?
            val bookId: Int
            val dudeId: Int
        }
        open class Borrowing(entity: Entity = Companion): Instance(entity), BorrowingFields {
            companion object: Entity("borrowing", bookshelf) {
                override fun new(): Borrowing = Borrowing()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Borrowing>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Borrowing>
                fun initialize() {
                    addField(Field("borrowingDate", "date", false, false))
                    addField(Field("restitutionDate", "date", false, false))
                    addField(Field("bookId", "int", false, false))
                    addField(Field("dudeId", "int", false, false))
                }
            }
            override var borrowingDate: LocalDate
                get() = getLocalDate("borrowingDate")!!
                set(v) { put("borrowingDate", v) }
            override var restitutionDate: LocalDate?
                get() = getLocalDate("restitutionDate")
                set(v) { put("restitutionDate", v) }
            override var bookId: Int
                get() = getInt("bookId")!!
                set(v) { put("bookId", v) }
            override var dudeId: Int
                get() = getInt("dudeId")!!
                set(v) { put("dudeId", v) }
        }
        interface TagFields {
            val tagId: Int
            val label: String
        }
        open class Tag(entity: Entity = Companion): Instance(entity), TagFields {
            companion object: Entity("tag", bookshelf) {
                override fun new(): Tag = Tag()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Tag?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Tag>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Tag>
                fun initialize() {
                    addField(Field("tagId", "serial", true, true))
                    addField(Field("label", "varchar(30)", false, false))
                }
            }
            override val tagId: Int
                get() = getInt("tagId")!!
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
        }
        interface BookTagFields {
            val bookId: Int
            val tagId: Int
        }
        open class BookTag(entity: Entity = Companion): Instance(entity), BookTagFields {
            companion object: Entity("bookTag", bookshelf) {
                override fun new(): BookTag = BookTag()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<BookTag>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<BookTag>
                fun initialize() {
                    addField(Field("bookId", "int", false, false))
                    addField(Field("tagId", "int", false, false))
                }
            }
            override var bookId: Int
                get() = getInt("bookId")!!
                set(v) { put("bookId", v) }
            override var tagId: Int
                get() = getInt("tagId")!!
                set(v) { put("tagId", v) }
        }
    }
}

