package com.republicate.skorm.bookshelf

/**
 * This file has been generated by the skorm gradle plugin.
 */

import com.republicate.kson.Json
import kotlinx.datetime.*
import com.republicate.skorm.*
import kotlin.jvm.JvmName

class ExampleDatabase(processor: Processor): Database("example", processor), MutableDatabase {
    companion object {
        lateinit var instance: Database
        private fun isInstantiated() = this::instance.isInitialized
        val bookshelf: BookshelfSchema by lazy { BookshelfSchema(instance) }
    }
    init {
        if (isInstantiated()) throw RuntimeException("ExampleDatabase instance already created")
        instance = this
    }
    override fun initialize() {
BookshelfSchema.Dude.initialize()
BookshelfSchema.Author.initialize()
BookshelfSchema.Book.initialize()
BookshelfSchema.Borrowing.initialize()
BookshelfSchema.Tag.initialize()
BookshelfSchema.BookTag.initialize()
        super.initialize()
    }
    class BookshelfSchema(db: Database): Schema("bookshelf", db), MutableSchema {
        enum class Genre {
            fiction,
            novel,
            essay,
            poetry
        }
        interface DudeFields {
            val dudeId: Int
            val name: String
        }
        open class Dude(entity: Entity = Companion): Instance(entity), MutableInstance, DudeFields {
            companion object: Entity("dude", bookshelf), MutableEntity {
                override fun new(): Dude = Dude()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Dude?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Dude>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Dude>
                fun initialize() {
                    addField(Field("dudeId", "serial", true, true))
                    addField(Field("name", "varchar(100)", false, false))
                }
            }
            override val dudeId: Int
                get() = getInt("dudeId")!!
            override var name: String
                get() = getString("name")!!
                set(v) { put("name", v) }
        }
        interface AuthorFields {
            val authorId: Int
            val name: String
        }
        open class Author(entity: Entity = Companion): Instance(entity), MutableInstance, AuthorFields {
            companion object: Entity("author", bookshelf), MutableEntity {
                override fun new(): Author = Author()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Author?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Author>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Author>
                fun initialize() {
                    addField(Field("authorId", "serial", true, true))
                    addField(Field("name", "varchar(100)", false, false))
                }
            }
            override val authorId: Int
                get() = getInt("authorId")!!
            override var name: String
                get() = getString("name")!!
                set(v) { put("name", v) }
            // reverse foreign key
            suspend fun books(): Sequence<ExampleDatabase.BookshelfSchema.Book> = query("books")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("books")
            fun booksBlocking(): List<ExampleDatabase.BookshelfSchema.Book> = blocking { books().toList() }
            // attribute Author.countInGenre
            suspend fun `countInGenre`(genre: Genre) = eval<Int>("countInGenre", genre)
            @JvmName("countInGenre")
            fun countInGenreBlocking(genre: Genre) = blocking { `countInGenre`(genre) }
            // attribute Author.catalog
            suspend fun `catalog`() = query<Catalog>("catalog")
            @JvmName("catalog")
            fun catalogBlocking() = blocking { `catalog`().toList() }
        }
        interface BookFields {
            val bookId: Int
            val title: String
            val genre: Genre
            val donor: Int?
            val authorId: Int
        }
        open class Book(entity: Entity = Companion): Instance(entity), MutableInstance, BookFields {
            companion object: Entity("book", bookshelf), MutableEntity {
                override fun new(): Book = Book()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Book?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Book>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Book>
                fun initialize() {
                    addField(Field("bookId", "serial", true, true))
                    addField(Field("title", "varchar(100)", false, false))
                    addField(Field("genre", "enum('fiction','novel','essay','poetry')", false, false))
                    addField(Field("donor", "int", false, false))
                    addField(Field("authorId", "int", false, false))
                }
            }
            override val bookId: Int
                get() = getInt("bookId")!!
            override var title: String
                get() = getString("title")!!
                set(v) { put("title", v) }
            override var genre: Genre
                get() = getString("genre")!!.let { Genre.valueOf(it) }
                set(v) { put("genre", v.toString()) }
            override var donor: Int?
                get() = getInt("donor")
                set(v) { put("donor", v) }
            override var authorId: Int
                get() = getInt("authorId")!!
                set(v) { put("authorId", v) }
            // forward foreign key
            suspend fun donor(): ExampleDatabase.BookshelfSchema.Dude? = retrieve("donor")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("donor")
            fun donorBlocking(): ExampleDatabase.BookshelfSchema.Dude? = blocking { donor() }
            // forward foreign key
            suspend fun author(): ExampleDatabase.BookshelfSchema.Author = retrieve("author")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("author")
            fun authorBlocking(): ExampleDatabase.BookshelfSchema.Author = blocking { author() }
            // left to right n-n join
            suspend fun tags(): Sequence<ExampleDatabase.BookshelfSchema.Tag> = query("tags")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("tags")
            fun tagsBlocking(): List<ExampleDatabase.BookshelfSchema.Tag> = blocking { tags().toList() }
            // attribute Book.currentBorrower
            suspend fun `currentBorrower`() = retrieve<CurrentBorrower?>("currentBorrower") as CurrentBorrower?
            @JvmName("currentBorrower")
            fun currentBorrowerBlocking() = blocking { `currentBorrower`() }
            // attribute Book.lend
            suspend fun `lend`(dude_id: Long) = perform("lend", dude_id)
            // attribute Book.restitute
            suspend fun `restitute`() = perform("restitute")
            // attribute Book.returnFrom
            suspend fun `returnFrom`(dude_id: Long ,returned_on: LocalDate) = perform("returnFrom", mapOf("dudeId" to dude_id, "returnedOn" to returned_on))
            // attribute Book.stats
            suspend fun `stats`() = retrieve<Stats>("stats") as Stats
            @JvmName("stats")
            fun statsBlocking() = blocking { `stats`() }
        }
        interface BorrowingFields {
            val borrowingDate: LocalDate
            val restitutionDate: LocalDate?
            val bookId: Int
            val dudeId: Int
        }
        open class Borrowing(entity: Entity = Companion): Instance(entity), MutableInstance, BorrowingFields {
            companion object: Entity("borrowing", bookshelf), MutableEntity {
                override fun new(): Borrowing = Borrowing()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Borrowing>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Borrowing>
                fun initialize() {
                    addField(Field("borrowingDate", "date", false, false))
                    addField(Field("restitutionDate", "date", false, false))
                    addField(Field("bookId", "int", false, false))
                    addField(Field("dudeId", "int", false, false))
                }
            }
            override var borrowingDate: LocalDate
                get() = getLocalDate("borrowingDate")!!
                set(v) { put("borrowingDate", v) }
            override var restitutionDate: LocalDate?
                get() = getLocalDate("restitutionDate")
                set(v) { put("restitutionDate", v) }
            override var bookId: Int
                get() = getInt("bookId")!!
                set(v) { put("bookId", v) }
            override var dudeId: Int
                get() = getInt("dudeId")!!
                set(v) { put("dudeId", v) }
            // forward foreign key
            suspend fun book(): ExampleDatabase.BookshelfSchema.Book = retrieve("book")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("book")
            fun bookBlocking(): ExampleDatabase.BookshelfSchema.Book = blocking { book() }
            // forward foreign key
            suspend fun dude(): ExampleDatabase.BookshelfSchema.Dude = retrieve("dude")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("dude")
            fun dudeBlocking(): ExampleDatabase.BookshelfSchema.Dude = blocking { dude() }
        }
        interface TagFields {
            val tagId: Int
            val label: String
        }
        open class Tag(entity: Entity = Companion): Instance(entity), MutableInstance, TagFields {
            companion object: Entity("tag", bookshelf), MutableEntity {
                override fun new(): Tag = Tag()
                @Suppress("UNCHECKED_CAST")
                override suspend fun fetch(vararg key: Any) = super.fetch(*key) as Tag?
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<Tag>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<Tag>
                fun initialize() {
                    addField(Field("tagId", "serial", true, true))
                    addField(Field("label", "varchar(30)", false, false))
                }
            }
            override val tagId: Int
                get() = getInt("tagId")!!
            override var label: String
                get() = getString("label")!!
                set(v) { put("label", v) }
            // right to left n-n join
            suspend fun books(): Sequence<ExampleDatabase.BookshelfSchema.Book> = query("books")
            // its blocking twin: what a reflection-driven caller reaches as `$join.name()`
            @JvmName("books")
            fun booksBlocking(): List<ExampleDatabase.BookshelfSchema.Book> = blocking { books().toList() }
        }
        interface BookTagFields {
            val bookId: Int
            val tagId: Int
        }
        open class BookTag(entity: Entity = Companion): Instance(entity), MutableInstance, BookTagFields {
            companion object: Entity("bookTag", bookshelf), MutableEntity {
                override fun new(): BookTag = BookTag()
                @Suppress("UNCHECKED_CAST")
                override suspend fun browse() = super.browse() as Sequence<BookTag>
                @Suppress("UNCHECKED_CAST")
                override suspend operator fun iterator() = super.iterator() as Iterator<BookTag>
                fun initialize() {
                    addField(Field("bookId", "int", false, false))
                    addField(Field("tagId", "int", false, false))
                }
            }
            override var bookId: Int
                get() = getInt("bookId")!!
                set(v) { put("bookId", v) }
            override var tagId: Int
                get() = getInt("tagId")!!
                set(v) { put("tagId", v) }
        }
        // attribute bookshelf.booksCount
        suspend fun `booksCount`() = eval<Int>("booksCount")
        @JvmName("booksCount")
        fun booksCountBlocking() = blocking { `booksCount`() }
        // attribute bookshelf.newBookBy
        suspend fun `newBookBy`(author_name: String ,title: String) = perform("newBookBy", mapOf("authorName" to author_name, "title" to title))
    }
}

