-- database example

-- schema bookshelf
DROP SCHEMA IF EXISTS bookshelf CASCADE;
CREATE SCHEMA bookshelf;
SET SCHEMA bookshelf;
CREATE DOMAIN enum_genre AS VARCHAR(7) CHECK (VALUE IN ('fiction', 'novel', 'essay', 'poetry'));
CREATE TABLE dude (
  dude_id integer generated by default as identity NOT NULL,
  name varchar(100) NOT NULL UNIQUE,
  PRIMARY KEY (dude_id)
);


CREATE TABLE author (
  author_id integer generated by default as identity NOT NULL,
  name varchar(100) NOT NULL,
  PRIMARY KEY (author_id)
);


CREATE TABLE book (
  book_id integer generated by default as identity NOT NULL,
  title varchar(100) NOT NULL,
  genre enum_genre NOT NULL,
  donor integer,
  author_id integer NOT NULL,
  PRIMARY KEY (book_id)
);


CREATE TABLE borrowing (
  borrowing_date date NOT NULL,
  restitution_date date,
  book_id integer NOT NULL,
  dude_id integer NOT NULL
);


CREATE TABLE tag (
  tag_id integer generated by default as identity NOT NULL,
  label varchar(30) NOT NULL,
  PRIMARY KEY (tag_id)
);


CREATE TABLE book_tag (
  book_id integer NOT NULL,
  tag_id integer NOT NULL
);

ALTER TABLE book ADD CONSTRAINT book_donor_fk FOREIGN KEY (donor) REFERENCES dude (dude_id);
ALTER TABLE book ADD CONSTRAINT book_author_fk FOREIGN KEY (author_id) REFERENCES author (author_id);
ALTER TABLE borrowing ADD CONSTRAINT borrowing_book_fk FOREIGN KEY (book_id) REFERENCES book (book_id);
ALTER TABLE borrowing ADD CONSTRAINT borrowing_dude_fk FOREIGN KEY (dude_id) REFERENCES dude (dude_id);
ALTER TABLE book_tag ADD CONSTRAINT book_tag_book_fk FOREIGN KEY (book_id) REFERENCES book (book_id) ON DELETE CASCADE;
ALTER TABLE book_tag ADD CONSTRAINT book_tag_tag_fk FOREIGN KEY (tag_id) REFERENCES tag (tag_id) ON DELETE CASCADE;
